name: commenteer

services:
  app:
    image: ghcr.io/cork89/commenteer:main
    container_name: commenteer
    ports:
      - "8090:8090"
    networks:
      - app-network
    secrets:
      - .env.local
    environment:
      POSTGRES_HOST: local_pgdb
      .env.local: /run/secrets/.env.local
  imgproxy:
    image: darthsim/imgproxy:latest
    container_name: imgproxy
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - IMGPROXY_ALLOW_ORIGIN=*
      - IMGPROXY_ALLOWED_SOURCES=https://*.reddit.com/,https://i.redd.it/,https://i.imgur.com/,https://b.thumbs.redditmedia.com/
      - IMGPROXY_WATERMARK_URL=https://pub-593a43bc7b42437089b8412f046d013b.r2.dev/madewith2.webp
      - IMGPROXY_KEY=${IMGPROXY_KEY_HEX}
      - IMGPROXY_SALT=${IMGPROXY_SALT_HEX}
  postgres:
    image: postgres:latest
    container_name: local_pgdb
    restart: always
    networks:
      - app-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    networks:
      - app-network
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
secrets:
  .env.local:
    file: ./run/secrets/.env.local
networks:
  app-network:
    driver: bridge
volumes:
  local_pgdata:
  pgadmin-data:
  