name: commenteer

services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  reverse-proxy:
    image: traefik:v3.1
    command: 
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificateresolvers.myresolver.acme.tlschallenge=true"
      - "--certificateresolvers.myresolver.acme.email=support@commenteer.dev"
      - "--certificateresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "entrypoints.web.address=:80"
      - "entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    image: cork89/commenteer-app:latest
    container_name: commenteer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`commenteer.dev`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      mode: replicated
      replicas: 3
    secrets:
      - .env.prod
    environment:
      POSTGRES_HOST: local_pgdb
      .env.prod: /run/secrets/.env.prod
    networks:
      - app-network
  imgproxy:
    image: darthsim/imgproxy:latest
    container_name: imgproxy
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - IMGPROXY_ALLOW_ORIGIN=*
      - IMGPROXY_ALLOWED_SOURCES=https://*.reddit.com/,https://i.redd.it/,https://i.imgur.com/,https://b.thumbs.redditmedia.com/
      - IMGPROXY_WATERMARK_URL=https://i.commenteer.dev/madewith2.webp
      - IMGPROXY_KEY=${IMGPROXY_KEY_HEX}
      - IMGPROXY_SALT=${IMGPROXY_SALT_HEX}
  postgres:
    image: postgres:latest
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - local_pgdata:/var/lib/postgresql/data
secrets:
  .env.local:
    file: .env.prod
networks:
  app-network:
    driver: bridge
volumes:
  local_pgdata:
  pgadmin-data:
  letsencrypt:
  