name: commenteer

services:
  app:
    # build:
    #   dockerfile: Dockerfile
    #   context: .
    #   target: base
    image: cork89/commenteer-app:latest
    container_name: commenteer
    ports:
      - "8090:8090"
    networks:
      - app-network
  imgproxy:
    image: darthsim/imgproxy:latest
    container_name: imgproxy
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - IMGPROXY_ALLOW_ORIGIN=*
      - IMGPROXY_ALLOWED_SOURCES=*
    #   # Add imgproxy configuration environment variables if needed
    #   - IMGPROXY_KEY=your_key
    #   - IMGPROXY_SALT=your_salt
    #   - IMGPROXY_ALLOWED_SOURCES=https://example.com
  postgres:
    image: postgres:latest
    container_name: local_pgdb
    restart: always
    networks:
      - app-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    networks:
      - app-network
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
networks:
  app-network:
    driver: bridge
volumes:
  local_pgdata:
  pgadmin-data:
  