# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: tests

on: [workflow_call]
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Build
      run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -v ./...

    - name: Test
      run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go test -v ./...
